// Generated by Copilot
import ErrorBoundaryWrapper from "@/components/ErrorBoundaryWrapper";
import CellsContent from "./CellsContent";

export const metadata = {
  title: "Cell Management",
  description: "View, create, update, and delete cell data for medical imaging",
};

export default function CellsPage() {
  return (
    <ErrorBoundaryWrapper
      appName="CrohnScope Cell Management"
      showHelpLink={true}
    >
      <CellsContent />
    </ErrorBoundaryWrapper>
  );
}
