// Generated by Copilot
import apiClient from "./client";

/**
 * Interface for AI model status information
 */
export interface ModelStatus {
  isOnline: boolean;
  isTraining: boolean;
  accuracy: number;
  lastTrainingDate: string;
}

/**
 * Get AI model status
 * @returns Promise with the model status
 */
export const getModelStatus = async (): Promise<ModelStatus> => {
  const response = await apiClient.get<ModelStatus>("/ai/status");
  return response.data;
};

/**
 * Start model training
 * @returns Promise with training status
 */
export const startTraining = async (): Promise<{ message: string }> => {
  const response = await apiClient.post("/ai/train");
  return response.data;
};

/**
 * Stop model training
 * @returns Promise with status message
 */
export const stopTraining = async (): Promise<{ message: string }> => {
  const response = await apiClient.post("/ai/stop-training");
  return response.data;
};
