// Generated by Copilot
import ErrorBoundaryWrapper from "@/components/ErrorBoundaryWrapper";
import SegmentationContent from "./SegmentationContent";

export const metadata = {
  title: "Segmentation Canvas",
  description: "Segmentation Canvas for CrohnScope",
};

export default function SegmentationCanvas() {
  return (
    <ErrorBoundaryWrapper
      appName="CrohnScope - Segmentation"
      showHelpLink={true}
    >
      <SegmentationContent />
    </ErrorBoundaryWrapper>
  );
}
