// Generated by Copilot
import Image from "next/image";

interface SectionHeaderProps {
  isDone: boolean;
  isCollapsed: boolean;
  count: number;
  onToggle: () => void;
}

export default function SectionHeader({
  isDone,
  isCollapsed,
  count,
  onToggle,
}: SectionHeaderProps) {
  return (
    <>
      {/* Section header */}
      <div className="section-header">
        <h3 className="section-title" onClick={onToggle}>
          {isDone ? "Completed Images" : "Pending Images"}
          <span className="section-count">
            {Number.isNaN(count) ? 0 : count}
          </span>
        </h3>
        <div className="section-actions">
          <span
            className={`toggle-icon ${isCollapsed ? "collapsed" : "expanded"}`}
            onClick={onToggle}
          >
            <Image
              src="/svgs/chevron.svg"
              alt="Toggle"
              width={20}
              height={20}
              className="svg-icon"
            />
          </span>
        </div>
      </div>
    </>
  );
}
