// Generated by Copilot
import UploadButton from "@/components/UploadBtn";
import Image from "next/image";

interface SectionHeaderProps {
  isDone: boolean;
  isCollapsed: boolean;
  count: number;
  onToggle: () => void;
  onUpload?: (file: File) => Promise<void>;
}

export default function SectionHeader({
  isDone,
  isCollapsed,
  count,
  onToggle,
  onUpload,
}: SectionHeaderProps) {
  return (
    <>
      {/* Section header */}
      <div className="section-header">
        <h3 className="section-title" onClick={onToggle}>
          {isDone ? "Completed Images" : "Pending Images"}
          <span className="section-count">
            {Number.isNaN(count) ? 0 : count}
          </span>
        </h3>
        <div className="section-actions">
          <span
            className={`toggle-icon ${isCollapsed ? "collapsed" : "expanded"}`}
            onClick={onToggle}
          >
            <Image
              src="/svgs/chevron.svg"
              alt="Toggle"
              width={20}
              height={20}
              className="svg-icon"
            />
          </span>
        </div>
      </div>

      {/* Upload button outside of header - styled to match images grid width */}
      {/* Generated by Copilot */}
      {!isDone && !isCollapsed && onUpload && (
        <div className="upload-section">
          <UploadButton
            label="Upload Images"
            onUpload={onUpload}
            showIcon={true}
          />
        </div>
      )}
    </>
  );
}
