'use client';
// Generated by Copilot

import ErrorBoundaryWrapper from "@/components/ErrorBoundaryWrapper";
import PatientsContent from "./PatientsContent";

export default function Page() {
  return (
    <ErrorBoundaryWrapper appName="CrohnScope - Patients">
      <PatientsContent />
    </ErrorBoundaryWrapper>
  );
}
