// Generated by Copilot
import Image from "next/image";
import Link from "next/link";

interface HeaderProps {
  title: string;
}

const Header = ({ title }: HeaderProps) => {
  return (
    <header className="flex items-center justify-start p-4 border-b">
      <Link
        href="/data"
        className="flex items-center gap-2 px-3 py-1 text-sm bg-gray-100 rounded-md hover:bg-gray-200 text-black"
      >
        <Image src="/svgs/home.svg" alt="Home" width={16} height={16} />
        <span>Home</span>
      </Link>
      <h1 className="text-xxl font-semibold">{title}</h1>
    </header>
  );
};

export default Header;
