"use client";
// Generated by Copilot
import { ApiFeature } from "@/lib/api";
import SeverityUI from "./SeverityUI";

interface FeatureListProps {
  features: ApiFeature[];
  selectedFeature: ApiFeature | null;
  onSelect: (feature: ApiFeature) => void;
  onEdit: (feature: ApiFeature) => void;
  onDelete: (feature: ApiFeature) => void;
  editMode: "view" | "edit" | "add";
  maxSeverity: {
    value: number;
    setter: (value: number) => void;
  };
}

export default function FeatureList({
  features,
  selectedFeature,
  onSelect,
  onEdit,
  onDelete,
  editMode,
  maxSeverity,
}: FeatureListProps) {
  if (features.length === 0) {
    return (
      <div className="text-center py-12">
        <svg
          className="mx-auto h-12 w-12 text-gray-400"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          aria-hidden="true"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="1.5"
            d="M9 13h6m-3-3v6m5 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
          />
        </svg>
        <h3 className="mt-2 text-sm font-medium text-gray-900 dark:text-gray-100">
          No features found
        </h3>
        <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
          Get started by creating a new feature.
        </p>
      </div>
    );
  }

  return (
    <div className="overflow-x-auto">
      <table
        className="min-w-full"
        style={{
          background: "var(--card-bg)",
          border: "1px solid var(--card-border)",
        }}
      >
        <thead style={{ background: "var(--card-border)" }}>
          <tr>
            <th
              scope="col"
              className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider"
              style={{ color: "var(--text-muted)" }}
            >
              ID
            </th>
            <th
              scope="col"
              className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider"
              style={{ color: "var(--text-muted)" }}
            >
              Image
            </th>
            <th
              scope="col"
              className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider"
              style={{ color: "var(--text-muted)" }}
            >
              Name
            </th>
            <th
              scope="col"
              className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider"
              style={{ color: "var(--text-muted)" }}
            >
              Severity
            </th>
            <th
              scope="col"
              className="px-6 py-3 text-right text-xs font-medium uppercase tracking-wider"
              style={{ color: "var(--text-muted)" }}
            >
              Actions
            </th>
          </tr>
        </thead>
        <tbody style={{ background: "var(--card-bg)" }}>
          {features.map((feature, index) => (
            <tr
              key={feature.id}
              style={{
                borderBottom: "1px solid var(--card-border)",
                background:
                  selectedFeature?.id === feature.id
                    ? "var(--accent-light)"
                    : undefined,
              }}
              className={`hover:brightness-95 cursor-pointer`}
              onClick={() => {
                if (editMode === "view") {
                  onSelect(feature);
                }
              }}
            >
              <td
                className="px-6 py-4 whitespace-nowrap text-sm"
                style={{ color: "var(--text-muted)" }}
              >
                {index + 1}
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                {feature.img ? (
                  <img
                    src={`data:image/jpeg;base64,${feature.img}`}
                    alt={feature.name}
                    className="h-10 w-10 rounded-md object-cover"
                    style={{ border: "1px solid var(--card-border)" }}
                  />
                ) : (
                  <div
                    className="h-10 w-10 rounded-md flex items-center justify-center"
                    style={{
                      background: "var(--input-bg)",
                      border: "1px solid var(--card-border)",
                    }}
                  >
                    <svg
                      className="h-6 w-6"
                      style={{ color: "var(--text-muted)" }}
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="1.5"
                        d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"
                      />
                    </svg>
                  </div>
                )}
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <div
                  className="text-sm font-medium"
                  style={{ color: "var(--foreground)" }}
                >
                  {feature.name}
                </div>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                {feature.severity !== undefined ? (
                  <SeverityUI
                    current={feature.severity}
                    max={maxSeverity.value}
                  />
                ) : (
                  <div
                    className="text-sm"
                    style={{ color: "var(--text-muted)" }}
                  >
                    —
                  </div>
                )}
              </td>
              <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    onEdit(feature);
                  }}
                  style={{ color: "var(--accent)" }}
                  className="hover:underline mr-4"
                >
                  Edit
                </button>
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    onDelete(feature);
                  }}
                  style={{ color: "#ef4444" }}
                  className="hover:underline"
                >
                  Delete
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
