import { DataProvider } from "@/components/AnnotationCanvas/DataContext";
import ImagesNav from "./_images/component";
import "./styles.scss";

export const metadata = {
  title: {
    default: "Data Processing Hub",
    template: "%s | Data Processing Hub",
  },
  description: "A hub for processing data",
};

// TODO: make a aside for images fetching
// TODO:

// const FolderID = "1AA8UCcJfSOo4h7wagO24ShEwJEVop43s";

const Index = async (
  props: Readonly<{
    children: React.ReactNode;
    main: React.ReactNode;
    params: { system: string };
  }>
) => {
  const { children, main } = props;

  return (
    <DataProvider>
      <main>
        <ImagesNav />
        {main}
        {/* Early Access Footer - Generated by Copilot */}
        <footer className="early-access-footer">
          <div className="early-access-badge">Early Access</div>
          <span>
            CrohnScope v0.9.0 - This is a pre-release version, May 2025
          </span>
        </footer>
      </main>
    </DataProvider>
  );
};
export default Index;
