import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies, headers } from "next/headers";
import { redirect } from "next/navigation";
import { getUserByUsername } from "./_lib/auth";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "CrohnScope",
    template: "%s | CrohnScope",
  },

  description: "CrohnScope is a web application for Crohn's disease research.",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // get cookies
  // Generated by Copilot
  const cookieStore = await cookies();
  const uid = cookieStore.get("uid")?.value;
  const isAuthPage = (await headers())
    .get("x-current-path")
    ?.startsWith("/auth/");
  console.log(!isAuthPage);

  if (!isAuthPage && !(uid && getUserByUsername(uid))) redirect("/auth/login");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
