import { redirect } from "next/navigation";

// Generated by Copilot
export default function Home() {
  //! Redirect to /data, will be removed later
  redirect("/data");

  // This won't be rendered due to the redirect
  return null;
}
