"use server";

import { drive_v3 } from "googleapis";
import { Readable } from "stream";
import { DownloadFileFromDrive, getDriveClient } from "../../_lib/googledrive";
import { FileLister } from "./utils";

// TODO: Use env variable
const ParentFolderId = "1Tj0eBH6Ih7CyXl2TueAWRd6z5dU030WT";

export async function listWithData(folderId: string) {
  const fileLister = new FileLister();
  await fileLister.init();
  return fileLister.listWithData(folderId);
}
export async function listAsRawFiles(folderId: string) {
  const fileLister = new FileLister();
  await fileLister.init();
  return fileLister.listAsRawFiles(folderId);
}
export async function listDriveFiles(folderId: string) {
  const fileLister = new FileLister();
  await fileLister.init();
  return fileLister.listDriveFiles(folderId);
}
export async function DownloadFiles(
  files: {
    id: string;
    name: string;
    modifiedTime: string;
  }[]
) {
  const fileLister = new FileLister();
  await fileLister.init();
  return fileLister.DownloadFiles(files);
}

export async function CreateFolder({
  name,
  ParentDirectoryId,
}: {
  name: string;
  ParentDirectoryId: string;
}) {
  const drive = await getDriveClient();
  const fileMetadata = {
    name: name,
    mimeType: "application/vnd.google-apps.folder",
    parents: [ParentDirectoryId],
  };
  const res = await drive.files.create({
    requestBody: fileMetadata,
    fields: "id",
  });
  return res.data.id;
}

export async function UploadFile({
  file,
  inFolderId,
}: {
  file: File;
  inFolderId: string;
}) {
  const drive = await getDriveClient();
  const fileMetadata = {
    name: file.name.split(".")[0],
    parents: [inFolderId],
  };
  const media = {
    mimeType: file.type,
    body: Readable.from(Buffer.from(await file.arrayBuffer())),
  };
  const res = await drive.files.create({
    requestBody: fileMetadata,
    media,
    fields: "id",
  });
  return res.data.id;
}

export async function DeleteFile(fileId: string) {
  const drive = await getDriveClient();
  await drive.files.delete({
    fileId,
  });
}
// Generated by Copilot
export async function GetFile(fileId: string, name?: string) {
  const drive = await getDriveClient();
  try {
    return DownloadFileFromDrive(drive, fileId, name || "unknown");
  } catch (error: any) {
    if (error.response?.status === 404 && name) {
      // File not found, create a new one
      const newFileId = await CreateFolder({
        name,
        ParentDirectoryId: ParentFolderId,
      });
      return { message: "File not found. Created a new folder.", newFileId };
    }
    throw error; // Re-throw other errors
  }
}
