import React from "react";
import { DataProvider } from "./DataContext";
import ImagesNav from "./ImagesNav";
import "./styles.scss";

const imagesFolder = "images";
const masksFolder = "masks";
const datasetSchemaFile = "dataset.json";
const datasetMetadataFile = "metadata.csv";

export default function AnnotationCanvas({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <DataProvider>
      <main>
        <ImagesNav />
        {children}
        {/* Early Access Footer - Generated by Copilot */}
        <footer className="early-access-footer">
          <div className="early-access-badge">Early Access</div>
          <span>
            CrohnScope v0.9.0 - This is a pre-release version, May 2025
          </span>
        </footer>
      </main>
    </DataProvider>
  );
}
