"use client";
import React, { useState } from "react";
import { ApiImage } from "./api";
import ImagesNav from "./ImagesNav";
import "./styles.scss";
export default function AnnotationCanvas({
  children,
}: {
  children: React.JSX.Element;
}) {
  const [img, setImg] = useState<ApiImage | null>(null);
  return (
    <div className="workspace-container">
      <ImagesNav setImage={setImg} />
      <section className="workspace-content">
        {/* Generated by Copilot */}
        {React.cloneElement(children, { image: img })}
      </section>
    </div>
  );
}
