"use client";
import Image from "next/image";
import React, { useState } from "react";
import { Tab } from "./types";

// Generated by Copilot
export default function TabNavigation({
  tabs,
  selectedTab,
  setSelectedTab,
  overlayRef,
  isMarkingAllDone,
}: {
  tabs: Tab[];
  selectedTab: number;
  setSelectedTab: (index: number) => void;
  setTabs?: React.Dispatch<React.SetStateAction<Tab[]>>; // Made optional since we're removing cell operations
  overlayRef: React.RefObject<HTMLCanvasElement | null>;
  isMarkingAllDone: boolean;
}) {
  const [isMarkingDone, setIsMarkingDone] = useState(false);

  // Render tabs without edit/add/delete functionality
  return (
    <nav className="tabs">
      <div className="tab-buttons">
        {tabs.map((tab, index) => (
          <button
            key={index}
            className={`tab-button ${selectedTab === index ? "active" : ""} ${
              tabs[selectedTab].cell_id == tab.cell_id && isMarkingDone
                ? "is-processing"
                : ""
            } `}
            onClick={() => setSelectedTab(index)}
          >
            <span>{tab.name}</span>
            {tab.isDone && (
              <Image
                src="/svgs/tab-done.svg"
                alt="Done"
                width={16}
                height={16}
              />
            )}
          </button>
        ))}
      </div>
      {/* Mark current tab as done button removed - now handled by the dropdown menu */}
    </nav>
  );
}
