export type Point = { x: number; y: number };
// export type Mode = "draw" | "erase";
// Generated by Copilot
export const modes = ["draw", "erase", "select", "hand"] as const;
export type GlobalModes = (typeof modes)[number];
export type DrawModes = Exclude<GlobalModes, "select">;
export type SelectMode = Exclude<GlobalModes, "draw" | "erase">;

export const ModesLabels: Record<GlobalModes, string> = {
  draw: "Draw tool to mark regions on the image",
  erase: "Erase tool to remove marked regions",
  select: "Select tool to choose regions on the image",
  hand: "Hand tool to pan and move around the image",
};

export type Shape = {
  points: Point[];
  mode: DrawModes;
};

export type Mask = HTMLImageElement;

export type SaveSatues = {
  isSaving: boolean;
  isModified: boolean;
  isMarkingAllDone: boolean;
};

export type Tab = {
  mask_id: number;
  cell_id: number;
  name: string;
  mask: Mask;
  isRename: boolean;
  isDone: boolean;
};

export enum CellsNames {
  "Cryptes",
  "Granulom",
}

export type DatasetSchema = {
  image_id: string;
  cell_id: string;
  cell_state: "healthy" | "unhealthy";
  cell_name: CellsNames;
  mask_path: string;
};

export type labelMaskPairs = {
  [label: string]: Mask;
};

export type DataProcessingMode = "segmentation" | "classification";
