// Generated by Copilot
"use client";

import Image from "next/image";
import Link from "next/link";

export const DataManagementCard = () => (
  <Link href="/data/management" className="group">
    <div className="bg-gray-800 rounded-xl overflow-hidden shadow-lg border border-blue-500/30 hover:border-blue-400 transition-all duration-300 hover:shadow-blue-500/20 hover:shadow-xl h-full flex flex-col">
      <div className="bg-gradient-to-r from-blue-700 to-blue-500 h-3"></div>
      <div className="p-6 flex-grow">
        <div className="flex flex-col items-center mb-4">
          <div className="bg-blue-600/20 p-3 rounded-lg mb-3">
            <Image
              src="/svgs/upload.svg"
              alt="Data Management Icon"
              width={28}
              height={28}
              className="text-blue-400 svg-icon"
            />
          </div>
          <div className="text-center">
            <div className="bg-blue-900/30 text-blue-300 text-xs font-medium px-2 py-1 rounded-sm inline-block mb-1">
              STEP 1
            </div>
            <h3 className="text-xl font-bold text-white group-hover:text-blue-400 transition-colors">
              Data Management
            </h3>
          </div>
        </div>
        <p className="text-gray-300 mb-6 text-sm text-center">
          Import, organize, and manage your microscopy images and datasets
        </p>
        <ul className="text-gray-400 space-y-2 mb-6 text-sm">
          <li className="flex items-center">
            <span className="mr-2">•</span>
            Batch uploading
          </li>
          <li className="flex items-center">
            <span className="mr-2">•</span>
            Format conversion
          </li>
          <li className="flex items-center">
            <span className="mr-2">•</span>
            Metadata extraction
          </li>
        </ul>
      </div>
      <div className="px-6 py-3 bg-gray-900/50 flex justify-between items-center">
        <span className="text-blue-400 text-sm font-medium">Import Data</span>
        <div className="bg-blue-600/30 rounded-full p-1 group-hover:bg-blue-500 transition-colors">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="text-white"
          >
            <path d="M5 12h14M12 5l7 7-7 7" />
          </svg>
        </div>
      </div>
    </div>
  </Link>
);

export const CellSegmentationCard = () => (
  <Link href="/data/segmentation" className="group">
    <div className="bg-gray-800 rounded-xl overflow-hidden shadow-lg border border-indigo-500/30 hover:border-indigo-400 transition-all duration-300 hover:shadow-indigo-500/20 hover:shadow-xl h-full flex flex-col">
      <div className="bg-gradient-to-r from-indigo-700 to-indigo-500 h-3"></div>
      <div className="p-6 flex-grow">
        <div className="flex flex-col items-center mb-4">
          <div className="bg-indigo-600/20 p-3 rounded-lg mb-3">
            <Image
              src="/svgs/draw.svg"
              alt="Segmentation Icon"
              width={28}
              height={28}
              className="text-indigo-400 svg-icon"
            />
          </div>
          <div className="text-center">
            <div className="bg-indigo-900/30 text-indigo-300 text-xs font-medium px-2 py-1 rounded-sm inline-block mb-1">
              STEP 2
            </div>
            <h3 className="text-xl font-bold text-white group-hover:text-indigo-400 transition-colors">
              Cell Segmentation
            </h3>
          </div>
        </div>
        <p className="text-gray-300 mb-6 text-sm text-center">
          Precisely analyze and segment cell images with our AI-assisted tools
        </p>
        <ul className="text-gray-400 space-y-2 mb-6 text-sm">
          <li className="flex items-center">
            <span className="mr-2">•</span>
            AI-assisted detection
          </li>
          <li className="flex items-center">
            <span className="mr-2">•</span>
            Manual correction
          </li>
          <li className="flex items-center">
            <span className="mr-2">•</span>
            Export masks
          </li>
        </ul>
      </div>
      <div className="px-6 py-3 bg-gray-900/50 flex justify-between items-center">
        <span className="text-indigo-400 text-sm font-medium">
          Start Segmenting
        </span>
        <div className="bg-indigo-600/30 rounded-full p-1 group-hover:bg-indigo-500 transition-colors">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="text-white"
          >
            <path d="M5 12h14M12 5l7 7-7 7" />
          </svg>
        </div>
      </div>
    </div>
  </Link>
);

export const CellLabelingCard = () => (
  <Link href="/data/labeling" className="group">
    <div className="bg-gray-800 rounded-xl overflow-hidden shadow-lg border border-emerald-500/30 hover:border-emerald-400 transition-all duration-300 hover:shadow-emerald-500/20 hover:shadow-xl h-full flex flex-col">
      <div className="bg-gradient-to-r from-emerald-700 to-emerald-500 h-3"></div>
      <div className="p-6 flex-grow">
        <div className="flex flex-col items-center mb-4">
          <div className="bg-emerald-600/20 p-3 rounded-lg mb-3">
            <Image
              src="/svgs/checkmark.svg"
              alt="Labeling Icon"
              width={28}
              height={28}
              className="text-emerald-400 svg-icon"
            />
          </div>
          <div className="text-center">
            <div className="bg-emerald-900/30 text-emerald-300 text-xs font-medium px-2 py-1 rounded-sm inline-block mb-1">
              STEP 3
            </div>
            <h3 className="text-xl font-bold text-white group-hover:text-emerald-400 transition-colors">
              Cell Labeling
            </h3>
          </div>
        </div>
        <p className="text-gray-300 mb-6 text-sm text-center">
          Efficiently classify and label segmented cells for research and
          training
        </p>
        <ul className="text-gray-400 space-y-2 mb-6 text-sm">
          <li className="flex items-center">
            <span className="mr-2">•</span>
            Multi-class labeling
          </li>
          <li className="flex items-center">
            <span className="mr-2">•</span>
            Batch processing
          </li>
          <li className="flex items-center">
            <span className="mr-2">•</span>
            ML-ready exports
          </li>
        </ul>
      </div>
      <div className="px-6 py-3 bg-gray-900/50 flex justify-between items-center">
        <span className="text-emerald-400 text-sm font-medium">
          Start Labeling
        </span>
        <div className="bg-emerald-600/30 rounded-full p-1 group-hover:bg-emerald-500 transition-colors">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="text-white"
          >
            <path d="M5 12h14M12 5l7 7-7 7" />
          </svg>
        </div>
      </div>
    </div>
  </Link>
);

export const DiagnosticsCard = () => (
  <Link href="/data/diagnostics" className="group">
    <div className="bg-gray-800 rounded-xl overflow-hidden shadow-lg border border-amber-500/30 hover:border-amber-400 transition-all duration-300 hover:shadow-amber-500/20 hover:shadow-xl h-full flex flex-col">
      <div className="bg-gradient-to-r from-amber-700 to-amber-500 h-3"></div>
      <div className="p-6 flex-grow">
        <div className="flex flex-col items-center mb-4">
          <div className="bg-amber-600/20 p-3 rounded-lg mb-3">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="28"
              height="28"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              className="text-amber-400"
            >
              <path d="M8 2v4"></path>
              <path d="M16 2v4"></path>
              <path d="M9 14l2 2l4-4"></path>
              <rect width="18" height="18" x="3" y="4" rx="2"></rect>
              <path d="M3 10h18"></path>
            </svg>
          </div>
          <div className="text-center">
            <div className="bg-amber-900/30 text-amber-300 text-xs font-medium px-2 py-1 rounded-sm inline-block mb-1">
              STEP 4
            </div>
            <h3 className="text-xl font-bold text-white group-hover:text-amber-400 transition-colors">
              Diagnostics
            </h3>
          </div>
        </div>
        <p className="text-gray-300 mb-6 text-sm text-center">
          Classify images and provide diagnostic information for model training
        </p>
        <ul className="text-gray-400 space-y-2 mb-6 text-sm">
          <li className="flex items-center">
            <span className="mr-2">•</span>
            Clinical assessment
          </li>
          <li className="flex items-center">
            <span className="mr-2">•</span>
            Confidence ratings
          </li>
          <li className="flex items-center">
            <span className="mr-2">•</span>
            Collaborative review
          </li>
        </ul>
      </div>
      <div className="px-6 py-3 bg-gray-900/50 flex justify-between items-center">
        <span className="text-amber-400 text-sm font-medium">
          Start Diagnosing
        </span>
        <div className="bg-amber-600/30 rounded-full p-1 group-hover:bg-amber-500 transition-colors">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="text-white"
          >
            <path d="M5 12h14M12 5l7 7-7 7" />
          </svg>
        </div>
      </div>
    </div>
  </Link>
);
