import Image from "next/image";
import Link from "next/link";

// Generated by Copilot
export default function DashboardPage() {
  // Sample dataset statistics - would be fetched from API in production
  const datasetStats = {
    totalImages: "NaN",
    segmentedImages: "NaN",
    labeledImages: "NaN",
    lastTrainingDate: "N/A",
    accuracy: "NaN",
  };

  return (
    <div className="flex flex-col h-full bg-gradient-to-br from-gray-900 to-gray-800 text-white">
      {/* Header Section */}
      <div className="container mx-auto px-4 py-8 text-center">
        <h1 className="text-4xl md:text-5xl font-bold mb-3 text-blue-400">
          CrohnScope Dashboard
        </h1>
        <p className="text-xl text-gray-300 max-w-3xl mx-auto mb-4">
          Track your dataset creation progress and model performance.
          <Link
            href="/data"
            className="text-blue-400 underline hover:text-blue-300 ml-2"
          >
            Go to Data Processing
          </Link>
        </p>

        {/* Hub Status Overview */}
        <div className="bg-gray-800/50 border border-gray-700 rounded-lg p-4 max-w-3xl mx-auto my-6 flex flex-wrap justify-center gap-6">
          <div className="flex items-center">
            <div className="w-12 h-12 bg-blue-900/30 rounded-lg flex items-center justify-center mr-3">
              <Image
                src="/svgs/file.svg"
                alt="Images"
                width={24}
                height={24}
                className="text-blue-400 svg-icon"
              />
            </div>
            <div className="text-left">
              <p className="text-gray-400 text-sm">Total Images</p>
              <p className="text-2xl font-bold text-white">
                {datasetStats.totalImages}
              </p>
            </div>
          </div>

          <div className="flex items-center">
            <div className="w-12 h-12 bg-indigo-900/30 rounded-lg flex items-center justify-center mr-3">
              <Image
                src="/svgs/brush.svg"
                alt="Segmented"
                width={24}
                height={24}
                className="text-indigo-400 svg-icon"
              />
            </div>
            <div className="text-left">
              <p className="text-gray-400 text-sm">Segmented</p>
              <p className="text-2xl font-bold text-white">
                {datasetStats.segmentedImages}
              </p>
            </div>
          </div>

          <div className="flex items-center">
            <div className="w-12 h-12 bg-emerald-900/30 rounded-lg flex items-center justify-center mr-3">
              <Image
                src="/svgs/checkmark.svg"
                alt="Labeled"
                width={24}
                height={24}
                className="text-emerald-400 svg-icon"
              />
            </div>
            <div className="text-left">
              <p className="text-gray-400 text-sm">Labeled</p>
              <p className="text-2xl font-bold text-white">
                {datasetStats.labeledImages}
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Analytics Card - Generated by Copilot */}
      <div className="container mx-auto px-4 py-8 flex justify-center">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 max-w-4xl w-full">
          <div className="col-span-3">
            <div className="flex items-center justify-center gap-2 mb-6">
              <div className="h-[1px] w-16 bg-gray-700"></div>
              <h2 className="text-lg font-medium text-gray-300">
                Dataset Analytics
              </h2>
              <div className="h-[1px] w-16 bg-gray-700"></div>
            </div>
          </div>

          {/* Dataset Quality Card */}
          <div className="bg-gray-800 rounded-xl overflow-hidden shadow-lg border border-purple-500/30 p-5">
            <div className="flex items-center mb-4">
              <div className="bg-purple-900/20 p-2 rounded-lg mr-3">
                <Image
                  src="/svgs/chart.svg"
                  alt="Dataset Quality"
                  width={20}
                  height={20}
                  className="text-purple-400 svg-icon"
                />
              </div>
              <h3 className="text-lg font-bold text-white">Dataset Quality</h3>
            </div>
            <div className="mb-2">
              <div className="flex justify-between text-sm mb-1">
                <span className="text-gray-400">Model Accuracy</span>
                <span className="text-purple-300">
                  {datasetStats.accuracy}%
                </span>
              </div>
              <div className="w-full bg-gray-700 rounded-full h-2">
                <div
                  className="bg-gradient-to-r from-purple-600 to-purple-400 h-2 rounded-full"
                  style={{ width: `50%` }}
                ></div>
              </div>
            </div>
            <p className="text-gray-400 text-sm mt-3">
              Last trained on {datasetStats.lastTrainingDate}
            </p>
          </div>

          {/* Dataset Size Card */}
          <div className="bg-gray-800 rounded-xl overflow-hidden shadow-lg border border-blue-500/30 p-5">
            <div className="flex items-center mb-4">
              <div className="bg-blue-900/20 p-2 rounded-lg mr-3">
                <Image
                  src="/svgs/dataset.svg"
                  alt="Dataset Size"
                  width={20}
                  height={20}
                  className="text-blue-400 svg-icon"
                />
              </div>
              <h3 className="text-lg font-bold text-white">Dataset Size</h3>
            </div>
            <div className="flex flex-col">
              <div className="grid grid-cols-2 gap-2 mb-3">
                <div className="bg-gray-900/50 p-3 rounded text-center">
                  <p className="text-2xl font-bold text-blue-400">
                    {datasetStats.totalImages}
                  </p>
                  <p className="text-xs text-gray-400">Total Images</p>
                </div>
                <div className="bg-gray-900/50 p-3 rounded text-center">
                  <p className="text-2xl font-bold text-emerald-400">
                    {datasetStats.labeledImages}
                  </p>
                  <p className="text-xs text-gray-400">Labeled Images</p>
                </div>
              </div>
            </div>
            <p className="text-gray-400 text-sm mt-3">
              Contribute more images to improve results
            </p>
          </div>

          {/* Data Distribution Card */}
          <div className="bg-gray-800 rounded-xl overflow-hidden shadow-lg border border-amber-500/30 p-5">
            <div className="flex items-center mb-4">
              <div className="bg-amber-900/20 p-2 rounded-lg mr-3">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  className="text-amber-400"
                >
                  <path d="M2 12h5"></path>
                  <path d="M17 12h5"></path>
                  <path d="M12 2v5"></path>
                  <path d="M12 17v5"></path>
                  <circle cx="12" cy="12" r="10"></circle>
                  <circle cx="12" cy="12" r="4"></circle>
                </svg>
              </div>
              <h3 className="text-lg font-bold text-white">
                Data Distribution
              </h3>
            </div>
            <div className="flex flex-col">
              <div className="space-y-2 mb-3">
                <div>
                  <div className="flex justify-between text-xs mb-1">
                    <span className="text-gray-400">Normal Cells</span>
                    <span className="text-amber-300">62%</span>
                  </div>
                  <div className="w-full bg-gray-700 rounded-full h-1.5">
                    <div
                      className="bg-amber-500 h-1.5 rounded-full"
                      style={{ width: "62%" }}
                    ></div>
                  </div>
                </div>
                <div>
                  <div className="flex justify-between text-xs mb-1">
                    <span className="text-gray-400">Inflammatory</span>
                    <span className="text-amber-300">28%</span>
                  </div>
                  <div className="w-full bg-gray-700 rounded-full h-1.5">
                    <div
                      className="bg-amber-500 h-1.5 rounded-full"
                      style={{ width: "28%" }}
                    ></div>
                  </div>
                </div>
                <div>
                  <div className="flex justify-between text-xs mb-1">
                    <span className="text-gray-400">Abnormal</span>
                    <span className="text-amber-300">10%</span>
                  </div>
                  <div className="w-full bg-gray-700 rounded-full h-1.5">
                    <div
                      className="bg-amber-500 h-1.5 rounded-full"
                      style={{ width: "10%" }}
                    ></div>
                  </div>
                </div>
              </div>
            </div>
            <p className="text-gray-400 text-sm mt-3">
              More abnormal cell samples needed
            </p>
          </div>
        </div>
      </div>

      {/* Dataset Workflow Section - Generated by Copilot */}
      <div className="container mx-auto px-4 py-8 flex justify-center">
        <div className="max-w-4xl w-full bg-gray-800/50 border border-gray-700 rounded-xl p-6">
          <h2 className="text-2xl font-bold text-center text-gray-200 mb-6">
            Complete Dataset Creation Pipeline
          </h2>

          <div className="relative">
            {/* Connector Line */}
            <div className="absolute top-1/2 left-0 right-0 h-1 bg-gray-700 -translate-y-1/2 z-0"></div>

            {/* Workflow Steps */}
            <div className="flex justify-between relative z-10">
              {/* Step 1: Upload */}
              <div className="flex flex-col items-center">
                <div className="w-16 h-16 bg-gray-900 rounded-full border-4 border-gray-700 flex items-center justify-center mb-3">
                  <Image
                    src="/svgs/upload.svg"
                    alt="Upload"
                    width={24}
                    height={24}
                    className="text-blue-400 svg-icon"
                  />
                </div>
                <p className="text-center text-gray-300 font-medium">Upload</p>
                <p className="text-center text-gray-500 text-sm">
                  Import images
                </p>
              </div>

              {/* Step 2: Segment */}
              <div className="flex flex-col items-center">
                <div className="w-16 h-16 bg-gray-900 rounded-full border-4 border-gray-700 flex items-center justify-center mb-3">
                  <Image
                    src="/svgs/brush.svg"
                    alt="Segment"
                    width={24}
                    height={24}
                    className="text-indigo-400 svg-icon"
                  />
                </div>
                <p className="text-center text-gray-300 font-medium">Segment</p>
                <p className="text-center text-gray-500 text-sm">
                  Define cell boundaries
                </p>
              </div>

              {/* Step 3: Label */}
              <div className="flex flex-col items-center">
                <div className="w-16 h-16 bg-gray-900 rounded-full border-4 border-gray-700 flex items-center justify-center mb-3">
                  <Image
                    src="/svgs/checkmark.svg"
                    alt="Label"
                    width={24}
                    height={24}
                    className="text-emerald-400 svg-icon"
                  />
                </div>
                <p className="text-center text-gray-300 font-medium">Label</p>
                <p className="text-center text-gray-500 text-sm">
                  Classify cell types
                </p>
              </div>

              {/* Step 4: Export */}
              <div className="flex flex-col items-center">
                <div className="w-16 h-16 bg-gray-900 rounded-full border-4 border-gray-700 flex items-center justify-center mb-3">
                  <Image
                    src="/svgs/save.svg"
                    alt="Export"
                    width={24}
                    height={24}
                    className="text-amber-400 svg-icon"
                  />
                </div>
                <p className="text-center text-gray-300 font-medium">Export</p>
                <p className="text-center text-gray-500 text-sm">
                  Create ML datasets
                </p>
              </div>
            </div>
          </div>

          <div className="mt-8 p-4 bg-blue-900/20 border border-blue-900/40 rounded-lg">
            <div className="flex items-start">
              <div className="bg-blue-500/20 p-2 rounded-md mr-4">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  className="text-blue-400"
                >
                  <circle cx="12" cy="12" r="10"></circle>
                  <line x1="12" y1="16" x2="12" y2="12"></line>
                  <line x1="12" y1="8" x2="12.01" y2="8"></line>
                </svg>
              </div>
              <div>
                <h4 className="text-blue-400 font-medium text-lg mb-1">
                  Dataset Creation Progress
                </h4>
                <p className="text-gray-300 text-sm">
                  Your dataset is currently at{" "}
                  <span className="font-medium">N/A</span> completion. The last
                  model training run was on{" "}
                  <span className="font-medium">
                    {datasetStats.lastTrainingDate}
                  </span>{" "}
                  with an accuracy of{" "}
                  <span className="font-medium">{datasetStats.accuracy}%</span>.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* AI Model Training Section - Generated by Copilot */}
      <div className="container mx-auto px-4 pt-2 pb-12 flex justify-center">
        <div className="max-w-4xl w-full">
          <div className="flex items-center justify-center gap-2 mb-8">
            <div className="h-[1px] w-16 bg-gray-700"></div>
            <h2 className="text-lg font-medium text-gray-300">
              Model Training
            </h2>
            <div className="h-[1px] w-16 bg-gray-700"></div>
          </div>

          <div className="bg-gray-800/70 border border-gray-700 rounded-xl overflow-hidden">
            <div className="flex flex-col md:flex-row">
              {/* Training Info */}
              <div className="md:w-3/5 p-6">
                <div className="flex items-center mb-5">
                  <div className="bg-cyan-900/20 p-3 rounded-lg mr-4">
                    <Image
                      src="/svgs/model.svg"
                      alt="AI Model"
                      width={24}
                      height={24}
                      className="text-cyan-400 svg-icon"
                    />
                  </div>
                  <div>
                    <div className="bg-cyan-900/30 text-cyan-300 text-xs font-medium px-2 py-1 rounded-sm inline-block mb-1">
                      MODEL TRAINING
                    </div>
                    <h3 className="text-2xl font-bold text-white">
                      Convert Datasets to AI Models
                    </h3>
                  </div>
                </div>

                <p className="text-gray-300 mb-6">
                  Train machine learning models using your labeled Crohn's
                  disease cell datasets. Start training with as few as 500
                  labeled samples and continuously improve accuracy as your
                  dataset grows.
                </p>

                <div className="grid grid-cols-2 gap-4 mb-6">
                  <div className="bg-gray-900/50 p-4 rounded-lg">
                    <div className="text-xs text-gray-500 mb-1">ACCURACY</div>
                    <div className="text-2xl font-bold text-cyan-400">
                      {datasetStats.accuracy}%
                    </div>
                    <div className="text-xs text-gray-400 mt-1">
                      Current Model
                    </div>
                  </div>

                  <div className="bg-gray-900/50 p-4 rounded-lg">
                    <div className="text-xs text-gray-500 mb-1">
                      LAST TRAINED
                    </div>
                    <div className="text-2xl font-bold text-cyan-400">
                      {datasetStats.lastTrainingDate}
                    </div>
                    <div className="text-xs text-gray-400 mt-1">
                      v0.8.3 Model
                    </div>
                  </div>
                </div>

                <button className="bg-cyan-600 hover:bg-cyan-500 text-white py-2 px-6 rounded-md transition-colors flex items-center">
                  <span>Start New Training Run</span>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="16"
                    height="16"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    className="ml-2"
                  >
                    <line x1="12" y1="5" x2="12" y2="19"></line>
                    <polyline points="19 12 12 19 5 12"></polyline>
                  </svg>
                </button>
              </div>

              {/* Training Status Visualization */}
              <div className="md:w-2/5 bg-gradient-to-br from-gray-900 to-gray-800 p-6 flex items-center justify-center relative">
                <div className="absolute inset-0 opacity-10">
                  <svg width="100%" height="100%" viewBox="0 0 100 100">
                    <defs>
                      <pattern
                        id="smallGrid"
                        width="10"
                        height="10"
                        patternUnits="userSpaceOnUse"
                      >
                        <path
                          d="M 10 0 L 0 0 0 10"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="0.5"
                          className="text-gray-500"
                        />
                      </pattern>
                    </defs>
                    <rect width="100%" height="100%" fill="url(#smallGrid)" />
                  </svg>
                </div>

                <div className="w-48 h-48 rounded-full flex items-center justify-center relative">
                  <div className="absolute inset-0 rounded-full border-8 border-gray-700"></div>
                  <div
                    className="absolute inset-0 rounded-full border-8 border-cyan-500 border-t-transparent border-r-transparent border-b-transparent"
                    style={{ transform: "rotate(-45deg)" }}
                  ></div>
                  <div className="text-center">
                    <div className="text-4xl font-bold text-white">N/A</div>
                    <div className="text-cyan-400 text-sm">
                      Ready for training
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Training Steps */}
            <div className="grid grid-cols-1 sm:grid-cols-3 border-t border-gray-700">
              <div className="p-4 border-b sm:border-b-0 sm:border-r border-gray-700">
                <div className="text-sm text-gray-400 mb-1">Step 1</div>
                <div className="font-medium text-white">Prepare Dataset</div>
                <div className="text-xs text-gray-500 mt-1">
                  Label at least 500 images
                </div>
              </div>
              <div className="p-4 border-b sm:border-b-0 sm:border-r border-gray-700">
                <div className="text-sm text-gray-400 mb-1">Step 2</div>
                <div className="font-medium text-white">Configure Training</div>
                <div className="text-xs text-gray-500 mt-1">
                  Set model parameters
                </div>
              </div>
              <div className="p-4">
                <div className="text-sm text-gray-400 mb-1">Step 3</div>
                <div className="font-medium text-white">Monitor Progress</div>
                <div className="text-xs text-gray-500 mt-1">
                  Visualize training metrics
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Recent Work Section - Generated by Copilot */}
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-xl font-bold text-white">Recent Work</h3>
            <button className="text-blue-400 hover:text-blue-300 text-sm flex items-center transition-colors">
              View all
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                className="ml-1"
              >
                <path d="M5 12h14M12 5l7 7-7 7" />
              </svg>
            </button>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4 mb-6">
            {/* Recent Image Items */}
            {[...Array(4)].map((_, i) => (
              <div
                key={i}
                className="bg-gray-800 border border-gray-700 rounded-lg overflow-hidden group hover:border-blue-500/50 transition-colors"
              >
                <div className="aspect-square bg-gray-900 w-full relative">
                  <div className="absolute inset-0 flex items-center justify-center text-gray-600">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="32"
                      height="32"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="1"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
                      <circle cx="8.5" cy="8.5" r="1.5" />
                      <polyline points="21 15 16 10 5 21" />
                    </svg>
                  </div>
                  {i === 1 && (
                    <div className="absolute bottom-2 right-2 bg-indigo-500 text-white text-xs px-1.5 py-0.5 rounded">
                      Segmented
                    </div>
                  )}
                  {i === 2 && (
                    <div className="absolute bottom-2 right-2 bg-emerald-500 text-white text-xs px-1.5 py-0.5 rounded">
                      Labeled
                    </div>
                  )}
                </div>
                <div className="p-3">
                  <div className="text-sm text-gray-300 font-medium truncate">
                    {
                      [
                        "Sample_0123",
                        "Crohn_Cell_4587",
                        "Biopsy_8976",
                        "Control_2365",
                      ][i]
                    }
                    .jpg
                  </div>
                  <div className="text-xs text-gray-500 mt-1">
                    Edited {["2 hours", "1 day", "3 days", "1 week"][i]} ago
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Status footer - Generated by Copilot */}
      <div className="container mx-auto px-4 py-6 border-t border-gray-800 mt-auto">
        <div className="flex flex-col md:flex-row justify-between items-center text-gray-400 text-sm">
          <div className="mb-4 md:mb-0 flex items-center flex-wrap gap-3">
            <span className="bg-blue-900/30 text-blue-400 px-3 py-1 rounded-full font-medium">
              Dashboard
            </span>
            <Link
              href="/data"
              className="text-xs text-blue-400 hover:text-blue-300 transition-colors underline"
            >
              Switch to Data Processing
            </Link>
            <span className="text-gray-500">
              Last updated:{" "}
              {new Date().toLocaleDateString("en-US", {
                year: "numeric",
                month: "short",
                day: "numeric",
              })}
            </span>
          </div>
          <div className="flex flex-wrap items-center gap-6">
            <span className="flex items-center">
              <div className="w-2 h-2 bg-green-500 rounded-full mr-2"></div>
              Segmentation API: Online
            </span>
            <span className="flex items-center">
              <div className="w-2 h-2 bg-green-500 rounded-full mr-2"></div>
              Classification API: Online
            </span>
            <span className="flex items-center">
              <div className="w-2 h-2 bg-blue-500 rounded-full mr-2"></div>
              Training Engine: Standby
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
