// Generated by Copilot
import ErrorBoundaryWrapper from "@/components/ErrorBoundaryWrapper";
import ClassificationContent from "./content";

export const metadata = {
  title: "Feature Classification Canvas",
  description: "Feature Classification Canvas for HistoScope",
};

export default function FeatureClassificationCanvas() {
  return (
    <ErrorBoundaryWrapper
      appName="HistoScope - Feature Classification"
      showHelpLink={true}
    >
      <ClassificationContent />
    </ErrorBoundaryWrapper>
  );
}
