import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: {
    default: "Data Processing Hub",
    template: "%s | Data Processing Hub",
  },
  description: "A hub for processing data",
};

export default function DataProcessingPage() {
  // Current date to show last updated
  const currentDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });

  return (
    <div className="flex flex-col h-full bg-gradient-to-br from-gray-900 to-gray-800 text-white">
      {/* Header Section */}
      <div className="container mx-auto px-4 py-8 text-center">
        <h1 className="text-4xl md:text-5xl font-bold mb-3 text-blue-400">
          Data Processing Center
        </h1>
        <p className="text-xl text-gray-300 max-w-3xl mx-auto mb-4">
          Prepare, process, and manage your datasets for Crohn's disease
          research
        </p>

        <div className="bg-blue-900/20 border border-blue-900/40 rounded-lg p-4 max-w-3xl mx-auto my-6">
          <div className="flex items-start md:items-center">
            <div className="bg-blue-500/20 p-2 rounded-md mr-4">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="20"
                height="20"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                className="text-blue-400"
              >
                <circle cx="12" cy="12" r="10"></circle>
                <line x1="12" y1="16" x2="12" y2="12"></line>
                <line x1="12" y1="8" x2="12.01" y2="8"></line>
              </svg>
            </div>
            <div className="text-left">
              <h4 className="text-blue-400 font-medium text-lg mb-1">
                Data Processing Pipeline
              </h4>
              <p className="text-gray-300 text-sm">
                Process your raw data through our integrated pipeline: import,
                preprocess, segment, label, and export. Visit the{" "}
                <Link
                  href="/dashboard"
                  className="text-blue-400 underline hover:text-blue-300"
                >
                  dashboard
                </Link>{" "}
                to view your dataset analytics.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Data Workflow Section */}
      <div className="container mx-auto px-4 flex flex-col items-center">
        <div className="flex items-center justify-center gap-2 mb-6">
          <div className="h-[1px] w-20 bg-gray-700"></div>
          <h2 className="text-lg font-medium text-gray-300">
            Data Processing Tools
          </h2>
          <div className="h-[1px] w-20 bg-gray-700"></div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 max-w-5xl w-full">
          {/* Data Management Card - Generated by Copilot */}
          <Link href="/data/management" className="group">
            <div className="bg-gray-800 rounded-xl overflow-hidden shadow-lg border border-blue-500/30 hover:border-blue-400 transition-all duration-300 hover:shadow-blue-500/20 hover:shadow-xl h-full flex flex-col">
              <div className="bg-gradient-to-r from-blue-700 to-blue-500 h-3"></div>
              <div className="p-6 flex-grow">
                <div className="flex flex-col items-center mb-4">
                  <div className="bg-blue-600/20 p-3 rounded-lg mb-3">
                    <Image
                      src="/svgs/upload.svg"
                      alt="Data Management Icon"
                      width={28}
                      height={28}
                      className="text-blue-400 svg-icon"
                    />
                  </div>
                  <div className="text-center">
                    <div className="bg-blue-900/30 text-blue-300 text-xs font-medium px-2 py-1 rounded-sm inline-block mb-1">
                      STEP 1
                    </div>
                    <h3 className="text-xl font-bold text-white group-hover:text-blue-400 transition-colors">
                      Data Management
                    </h3>
                  </div>
                </div>
                <p className="text-gray-300 mb-6 text-sm text-center">
                  Import, organize, and manage your microscopy images and
                  datasets
                </p>
                <ul className="text-gray-400 space-y-2 mb-6 text-sm">
                  <li className="flex items-center">
                    <span className="mr-2">•</span>
                    Batch uploading
                  </li>
                  <li className="flex items-center">
                    <span className="mr-2">•</span>
                    Format conversion
                  </li>
                  <li className="flex items-center">
                    <span className="mr-2">•</span>
                    Metadata extraction
                  </li>
                </ul>
              </div>
              <div className="px-6 py-3 bg-gray-900/50 flex justify-between items-center">
                <span className="text-blue-400 text-sm font-medium">
                  Import Data
                </span>
                <div className="bg-blue-600/30 rounded-full p-1 group-hover:bg-blue-500 transition-colors">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="16"
                    height="16"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    className="text-white"
                  >
                    <path d="M5 12h14M12 5l7 7-7 7" />
                  </svg>
                </div>
              </div>
            </div>
          </Link>

          {/* Cell Segmentation Card */}
          <Link href="/data/segmentation" className="group">
            <div className="bg-gray-800 rounded-xl overflow-hidden shadow-lg border border-indigo-500/30 hover:border-indigo-400 transition-all duration-300 hover:shadow-indigo-500/20 hover:shadow-xl h-full flex flex-col">
              <div className="bg-gradient-to-r from-indigo-700 to-indigo-500 h-3"></div>
              <div className="p-6 flex-grow">
                <div className="flex flex-col items-center mb-4">
                  <div className="bg-indigo-600/20 p-3 rounded-lg mb-3">
                    <Image
                      src="/svgs/brush.svg"
                      alt="Segmentation Icon"
                      width={28}
                      height={28}
                      className="text-indigo-400 svg-icon"
                    />
                  </div>
                  <div className="text-center">
                    <div className="bg-indigo-900/30 text-indigo-300 text-xs font-medium px-2 py-1 rounded-sm inline-block mb-1">
                      STEP 2
                    </div>
                    <h3 className="text-xl font-bold text-white group-hover:text-indigo-400 transition-colors">
                      Cell Segmentation
                    </h3>
                  </div>
                </div>
                <p className="text-gray-300 mb-6 text-sm text-center">
                  Precisely analyze and segment cell images with our AI-assisted
                  tools
                </p>
                <ul className="text-gray-400 space-y-2 mb-6 text-sm">
                  <li className="flex items-center">
                    <span className="mr-2">•</span>
                    AI-assisted detection
                  </li>
                  <li className="flex items-center">
                    <span className="mr-2">•</span>
                    Manual correction
                  </li>
                  <li className="flex items-center">
                    <span className="mr-2">•</span>
                    Export masks
                  </li>
                </ul>
              </div>
              <div className="px-6 py-3 bg-gray-900/50 flex justify-between items-center">
                <span className="text-indigo-400 text-sm font-medium">
                  Start Segmenting
                </span>
                <div className="bg-indigo-600/30 rounded-full p-1 group-hover:bg-indigo-500 transition-colors">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="16"
                    height="16"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    className="text-white"
                  >
                    <path d="M5 12h14M12 5l7 7-7 7" />
                  </svg>
                </div>
              </div>
            </div>
          </Link>

          {/* Cell Labeling Card */}
          <Link href="/data/labeling" className="group">
            <div className="bg-gray-800 rounded-xl overflow-hidden shadow-lg border border-emerald-500/30 hover:border-emerald-400 transition-all duration-300 hover:shadow-emerald-500/20 hover:shadow-xl h-full flex flex-col">
              <div className="bg-gradient-to-r from-emerald-700 to-emerald-500 h-3"></div>
              <div className="p-6 flex-grow">
                <div className="flex flex-col items-center mb-4">
                  <div className="bg-emerald-600/20 p-3 rounded-lg mb-3">
                    <Image
                      src="/svgs/checkmark.svg"
                      alt="Labeling Icon"
                      width={28}
                      height={28}
                      className="text-emerald-400 svg-icon"
                    />
                  </div>
                  <div className="text-center">
                    <div className="bg-emerald-900/30 text-emerald-300 text-xs font-medium px-2 py-1 rounded-sm inline-block mb-1">
                      STEP 3
                    </div>
                    <h3 className="text-xl font-bold text-white group-hover:text-emerald-400 transition-colors">
                      Cell Labeling
                    </h3>
                  </div>
                </div>
                <p className="text-gray-300 mb-6 text-sm text-center">
                  Efficiently classify and label segmented cells for research
                  and training
                </p>
                <ul className="text-gray-400 space-y-2 mb-6 text-sm">
                  <li className="flex items-center">
                    <span className="mr-2">•</span>
                    Multi-class labeling
                  </li>
                  <li className="flex items-center">
                    <span className="mr-2">•</span>
                    Batch processing
                  </li>
                  <li className="flex items-center">
                    <span className="mr-2">•</span>
                    ML-ready exports
                  </li>
                </ul>
              </div>
              <div className="px-6 py-3 bg-gray-900/50 flex justify-between items-center">
                <span className="text-emerald-400 text-sm font-medium">
                  Start Labeling
                </span>
                <div className="bg-emerald-600/30 rounded-full p-1 group-hover:bg-emerald-500 transition-colors">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="16"
                    height="16"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    className="text-white"
                  >
                    <path d="M5 12h14M12 5l7 7-7 7" />
                  </svg>
                </div>
              </div>
            </div>
          </Link>

          {/* Diagnostics Card - Generated by Copilot */}
          <Link href="/data/diagnostics" className="group">
            <div className="bg-gray-800 rounded-xl overflow-hidden shadow-lg border border-amber-500/30 hover:border-amber-400 transition-all duration-300 hover:shadow-amber-500/20 hover:shadow-xl h-full flex flex-col">
              <div className="bg-gradient-to-r from-amber-700 to-amber-500 h-3"></div>
              <div className="p-6 flex-grow">
                <div className="flex flex-col items-center mb-4">
                  <div className="bg-amber-600/20 p-3 rounded-lg mb-3">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="28"
                      height="28"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      className="text-amber-400"
                    >
                      <path d="M8 2v4"></path>
                      <path d="M16 2v4"></path>
                      <path d="M9 14l2 2l4-4"></path>
                      <rect width="18" height="18" x="3" y="4" rx="2"></rect>
                      <path d="M3 10h18"></path>
                    </svg>
                  </div>
                  <div className="text-center">
                    <div className="bg-amber-900/30 text-amber-300 text-xs font-medium px-2 py-1 rounded-sm inline-block mb-1">
                      STEP 4
                    </div>
                    <h3 className="text-xl font-bold text-white group-hover:text-amber-400 transition-colors">
                      Diagnostics
                    </h3>
                  </div>
                </div>
                <p className="text-gray-300 mb-6 text-sm text-center">
                  Classify images and provide diagnostic information for model
                  training
                </p>
                <ul className="text-gray-400 space-y-2 mb-6 text-sm">
                  <li className="flex items-center">
                    <span className="mr-2">•</span>
                    Clinical assessment
                  </li>
                  <li className="flex items-center">
                    <span className="mr-2">•</span>
                    Confidence ratings
                  </li>
                  <li className="flex items-center">
                    <span className="mr-2">•</span>
                    Collaborative review
                  </li>
                </ul>
              </div>
              <div className="px-6 py-3 bg-gray-900/50 flex justify-between items-center">
                <span className="text-amber-400 text-sm font-medium">
                  Start Diagnosing
                </span>
                <div className="bg-amber-600/30 rounded-full p-1 group-hover:bg-amber-500 transition-colors">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="16"
                    height="16"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    className="text-white"
                  >
                    <path d="M5 12h14M12 5l7 7-7 7" />
                  </svg>
                </div>
              </div>
            </div>
          </Link>
        </div>
      </div>

      {/* Status footer */}
      <div className="container mx-auto px-4 py-6 border-t border-gray-800 mt-auto">
        <div className="flex flex-col md:flex-row justify-between items-center text-gray-400 text-sm">
          <div className="mb-4 md:mb-0 flex items-center flex-wrap gap-3">
            <span className="bg-blue-900/30 text-blue-400 px-3 py-1 rounded-full font-medium">
              Data Processing Center
            </span>
            <Link
              href="/dashboard"
              className="text-xs text-blue-400 hover:text-blue-300 transition-colors underline"
            >
              Switch to Dashboard
            </Link>
            <span className="text-gray-500">Last updated: {currentDate}</span>
          </div>
          <div className="flex flex-wrap items-center gap-6">
            <span className="flex items-center">
              <div className="w-2 h-2 bg-green-500 rounded-full mr-2"></div>
              Preprocessing API: Online
            </span>
            <span className="flex items-center">
              <div className="w-2 h-2 bg-green-500 rounded-full mr-2"></div>
              Segmentation API: Online
            </span>
            <span className="flex items-center">
              <div className="w-2 h-2 bg-green-500 rounded-full mr-2"></div>
              Storage: 1.2TB Available
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
