// Generated by Copilot
import { Dispatch, SetStateAction } from "react";
import LayerState, { State } from "./LayerState";

interface ClassificationToolbarProps {
  layerState: State;
  setLayerState: Dispatch<SetStateAction<State>>;
}

export default function ClassificationToolbar({
  layerState,
  setLayerState,
}: ClassificationToolbarProps) {
  return (
    <div className="layers-tools">
      <LayerState value={layerState} onChange={setLayerState} />
    </div>
  );
}
